version: '3.2'
services:
  jenkins:
      build:
       context: jenkins/
      privileged: true
      user: root
      ports:
        - 8888:8080
        - 50000:50000
      container_name: jenkins
      volumes:
          - /var/lib/docker/volumes/jenkins_data/_data:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          