apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8888
      name: "http"
      nodePort: 31234
      targetPort: 8080
    - port: 50000
      name: "slave"
      nodePort: 31235
      targetPort: 50000
  selector:
    app: jenkins