apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
     hostNetwork: true
     securityContext:
        runAsUser: 0
     containers:
      - name: my-jenkins
        image: 20170918/jenkins-kubectl:latest
        securityContext:
          privileged: true
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-socket
              mountPath: /var/run/docker.sock
     volumes:
        - name: jenkins-home
          hostPath: 
              path: /var/lib/docker/volumes/jenkins-home/_data
               
        - name: docker-socket
          hostPath: 
              path: /var/run/docker.sock
    
     imagePullSecrets:
               - name: regcred
      
          
          