apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8888
      name: "http"
      nodePort: 31234
      targetPort: 8080
  selector:
    app: jenkins