apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
       runAsUser: 0
      containers:
      - name: my-jenkins
        image: 20170918/jenkins:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-data
          hostPath: 
              path: /var/lib/docker/volumes/jenkins_data/_data
               
        - name: docker-socket
          hostPath: 
              path: /var/run/docker.sock
          
          