apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product-service
    role: rolling-update 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: tx-product-service
        image: 20170918/product-service:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
  strategy:
      type: RollingUpdate