kind: Service
apiVersion: v1
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
      app: product-service
  ports:
     - name: http
       port: 8080
       targetPort: 8080
  type: LoadBalancer